spring.application.name=api

# Server
server.port=8000

# OpenF1 API
openf1.base-url=https://api.openf1.org/v1

# Cache
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=3600s

logging.level.com.f1.api.client=INFO

# Datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=false
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s

# Exclure les fichiers qui ne doivent pas declencher un restart
spring.devtools.restart.exclude=static/**,public/**,templates/**