spring.application.name=api

# Server
server.port=8000

# OpenF1 API
openf1.base-url=https://api.openf1.org/v1

# Cache
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=3600s
